/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: pnpm content:manifest
 *
 * This file provides statically bundled content manifest data.
 * No runtime fs dependency - works in dev and production builds.
 */

import type { ContentType, Locale } from '@/types/content';

export interface ContentEntry {
  type: ContentType;
  locale: Locale;
  slug: string;
  extension: string;
  filePath: string;
  relativePath: string;
}

export interface ContentManifest {
  entries: ContentEntry[];
  byKey: Record<string, ContentEntry>;
}

export const CONTENT_MANIFEST: ContentManifest = {
  entries: [
  {
    "type": "posts",
    "locale": "en",
    "slug": "choosing-reliable-suppliers",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/choosing-reliable-suppliers.mdx",
    "relativePath": "content/posts/en/choosing-reliable-suppliers.mdx"
  },
  {
    "type": "posts",
    "locale": "en",
    "slug": "export-documentation-checklist",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/export-documentation-checklist.mdx",
    "relativePath": "content/posts/en/export-documentation-checklist.mdx"
  },
  {
    "type": "posts",
    "locale": "en",
    "slug": "guide-to-international-trade-terms",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/guide-to-international-trade-terms.mdx",
    "relativePath": "content/posts/en/guide-to-international-trade-terms.mdx"
  },
  {
    "type": "posts",
    "locale": "en",
    "slug": "quality-control-best-practices",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/quality-control-best-practices.mdx",
    "relativePath": "content/posts/en/quality-control-best-practices.mdx"
  },
  {
    "type": "posts",
    "locale": "en",
    "slug": "welcome-to-tucsenberg",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/welcome-to-tucsenberg.mdx",
    "relativePath": "content/posts/en/welcome-to-tucsenberg.mdx"
  },
  {
    "type": "posts",
    "locale": "zh",
    "slug": "choosing-reliable-suppliers",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/choosing-reliable-suppliers.mdx",
    "relativePath": "content/posts/zh/choosing-reliable-suppliers.mdx"
  },
  {
    "type": "posts",
    "locale": "zh",
    "slug": "export-documentation-checklist",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/export-documentation-checklist.mdx",
    "relativePath": "content/posts/zh/export-documentation-checklist.mdx"
  },
  {
    "type": "posts",
    "locale": "zh",
    "slug": "guide-to-international-trade-terms",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/guide-to-international-trade-terms.mdx",
    "relativePath": "content/posts/zh/guide-to-international-trade-terms.mdx"
  },
  {
    "type": "posts",
    "locale": "zh",
    "slug": "quality-control-best-practices",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/quality-control-best-practices.mdx",
    "relativePath": "content/posts/zh/quality-control-best-practices.mdx"
  },
  {
    "type": "posts",
    "locale": "zh",
    "slug": "welcome-to-tucsenberg",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/welcome-to-tucsenberg.mdx",
    "relativePath": "content/posts/zh/welcome-to-tucsenberg.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/en/about.mdx",
    "relativePath": "content/pages/en/about.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "faq",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/en/faq.mdx",
    "relativePath": "content/pages/en/faq.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/en/privacy.mdx",
    "relativePath": "content/pages/en/privacy.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/en/terms.mdx",
    "relativePath": "content/pages/en/terms.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/zh/about.mdx",
    "relativePath": "content/pages/zh/about.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "faq",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/zh/faq.mdx",
    "relativePath": "content/pages/zh/faq.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/zh/privacy.mdx",
    "relativePath": "content/pages/zh/privacy.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/zh/terms.mdx",
    "relativePath": "content/pages/zh/terms.mdx"
  },
  {
    "type": "products",
    "locale": "en",
    "slug": "hydraulic-pump-station",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/hydraulic-pump-station.mdx",
    "relativePath": "content/products/en/hydraulic-pump-station.mdx"
  },
  {
    "type": "products",
    "locale": "en",
    "slug": "industrial-control-panel",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/industrial-control-panel.mdx",
    "relativePath": "content/products/en/industrial-control-panel.mdx"
  },
  {
    "type": "products",
    "locale": "en",
    "slug": "industrial-valve-set",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/industrial-valve-set.mdx",
    "relativePath": "content/products/en/industrial-valve-set.mdx"
  },
  {
    "type": "products",
    "locale": "en",
    "slug": "led-industrial-lighting",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/led-industrial-lighting.mdx",
    "relativePath": "content/products/en/led-industrial-lighting.mdx"
  },
  {
    "type": "products",
    "locale": "en",
    "slug": "pneumatic-cylinder",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/pneumatic-cylinder.mdx",
    "relativePath": "content/products/en/pneumatic-cylinder.mdx"
  },
  {
    "type": "products",
    "locale": "en",
    "slug": "smart-sensor-module",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/smart-sensor-module.mdx",
    "relativePath": "content/products/en/smart-sensor-module.mdx"
  },
  {
    "type": "products",
    "locale": "en",
    "slug": "stainless-steel-fasteners",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/stainless-steel-fasteners.mdx",
    "relativePath": "content/products/en/stainless-steel-fasteners.mdx"
  },
  {
    "type": "products",
    "locale": "en",
    "slug": "variable-frequency-drive",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/variable-frequency-drive.mdx",
    "relativePath": "content/products/en/variable-frequency-drive.mdx"
  },
  {
    "type": "products",
    "locale": "zh",
    "slug": "hydraulic-pump-station",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/hydraulic-pump-station.mdx",
    "relativePath": "content/products/zh/hydraulic-pump-station.mdx"
  },
  {
    "type": "products",
    "locale": "zh",
    "slug": "industrial-control-panel",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/industrial-control-panel.mdx",
    "relativePath": "content/products/zh/industrial-control-panel.mdx"
  },
  {
    "type": "products",
    "locale": "zh",
    "slug": "industrial-valve-set",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/industrial-valve-set.mdx",
    "relativePath": "content/products/zh/industrial-valve-set.mdx"
  },
  {
    "type": "products",
    "locale": "zh",
    "slug": "led-industrial-lighting",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/led-industrial-lighting.mdx",
    "relativePath": "content/products/zh/led-industrial-lighting.mdx"
  },
  {
    "type": "products",
    "locale": "zh",
    "slug": "pneumatic-cylinder",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/pneumatic-cylinder.mdx",
    "relativePath": "content/products/zh/pneumatic-cylinder.mdx"
  },
  {
    "type": "products",
    "locale": "zh",
    "slug": "smart-sensor-module",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/smart-sensor-module.mdx",
    "relativePath": "content/products/zh/smart-sensor-module.mdx"
  },
  {
    "type": "products",
    "locale": "zh",
    "slug": "stainless-steel-fasteners",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/stainless-steel-fasteners.mdx",
    "relativePath": "content/products/zh/stainless-steel-fasteners.mdx"
  },
  {
    "type": "products",
    "locale": "zh",
    "slug": "variable-frequency-drive",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/variable-frequency-drive.mdx",
    "relativePath": "content/products/zh/variable-frequency-drive.mdx"
  }
],
  byKey: {
  "posts/en/choosing-reliable-suppliers": {
    "type": "posts",
    "locale": "en",
    "slug": "choosing-reliable-suppliers",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/choosing-reliable-suppliers.mdx",
    "relativePath": "content/posts/en/choosing-reliable-suppliers.mdx"
  },
  "posts/en/export-documentation-checklist": {
    "type": "posts",
    "locale": "en",
    "slug": "export-documentation-checklist",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/export-documentation-checklist.mdx",
    "relativePath": "content/posts/en/export-documentation-checklist.mdx"
  },
  "posts/en/guide-to-international-trade-terms": {
    "type": "posts",
    "locale": "en",
    "slug": "guide-to-international-trade-terms",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/guide-to-international-trade-terms.mdx",
    "relativePath": "content/posts/en/guide-to-international-trade-terms.mdx"
  },
  "posts/en/quality-control-best-practices": {
    "type": "posts",
    "locale": "en",
    "slug": "quality-control-best-practices",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/quality-control-best-practices.mdx",
    "relativePath": "content/posts/en/quality-control-best-practices.mdx"
  },
  "posts/en/welcome-to-tucsenberg": {
    "type": "posts",
    "locale": "en",
    "slug": "welcome-to-tucsenberg",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/en/welcome-to-tucsenberg.mdx",
    "relativePath": "content/posts/en/welcome-to-tucsenberg.mdx"
  },
  "posts/zh/choosing-reliable-suppliers": {
    "type": "posts",
    "locale": "zh",
    "slug": "choosing-reliable-suppliers",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/choosing-reliable-suppliers.mdx",
    "relativePath": "content/posts/zh/choosing-reliable-suppliers.mdx"
  },
  "posts/zh/export-documentation-checklist": {
    "type": "posts",
    "locale": "zh",
    "slug": "export-documentation-checklist",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/export-documentation-checklist.mdx",
    "relativePath": "content/posts/zh/export-documentation-checklist.mdx"
  },
  "posts/zh/guide-to-international-trade-terms": {
    "type": "posts",
    "locale": "zh",
    "slug": "guide-to-international-trade-terms",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/guide-to-international-trade-terms.mdx",
    "relativePath": "content/posts/zh/guide-to-international-trade-terms.mdx"
  },
  "posts/zh/quality-control-best-practices": {
    "type": "posts",
    "locale": "zh",
    "slug": "quality-control-best-practices",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/quality-control-best-practices.mdx",
    "relativePath": "content/posts/zh/quality-control-best-practices.mdx"
  },
  "posts/zh/welcome-to-tucsenberg": {
    "type": "posts",
    "locale": "zh",
    "slug": "welcome-to-tucsenberg",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/posts/zh/welcome-to-tucsenberg.mdx",
    "relativePath": "content/posts/zh/welcome-to-tucsenberg.mdx"
  },
  "pages/en/about": {
    "type": "pages",
    "locale": "en",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/en/about.mdx",
    "relativePath": "content/pages/en/about.mdx"
  },
  "pages/en/faq": {
    "type": "pages",
    "locale": "en",
    "slug": "faq",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/en/faq.mdx",
    "relativePath": "content/pages/en/faq.mdx"
  },
  "pages/en/privacy": {
    "type": "pages",
    "locale": "en",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/en/privacy.mdx",
    "relativePath": "content/pages/en/privacy.mdx"
  },
  "pages/en/terms": {
    "type": "pages",
    "locale": "en",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/en/terms.mdx",
    "relativePath": "content/pages/en/terms.mdx"
  },
  "pages/zh/about": {
    "type": "pages",
    "locale": "zh",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/zh/about.mdx",
    "relativePath": "content/pages/zh/about.mdx"
  },
  "pages/zh/faq": {
    "type": "pages",
    "locale": "zh",
    "slug": "faq",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/zh/faq.mdx",
    "relativePath": "content/pages/zh/faq.mdx"
  },
  "pages/zh/privacy": {
    "type": "pages",
    "locale": "zh",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/zh/privacy.mdx",
    "relativePath": "content/pages/zh/privacy.mdx"
  },
  "pages/zh/terms": {
    "type": "pages",
    "locale": "zh",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/pages/zh/terms.mdx",
    "relativePath": "content/pages/zh/terms.mdx"
  },
  "products/en/hydraulic-pump-station": {
    "type": "products",
    "locale": "en",
    "slug": "hydraulic-pump-station",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/hydraulic-pump-station.mdx",
    "relativePath": "content/products/en/hydraulic-pump-station.mdx"
  },
  "products/en/industrial-control-panel": {
    "type": "products",
    "locale": "en",
    "slug": "industrial-control-panel",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/industrial-control-panel.mdx",
    "relativePath": "content/products/en/industrial-control-panel.mdx"
  },
  "products/en/industrial-valve-set": {
    "type": "products",
    "locale": "en",
    "slug": "industrial-valve-set",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/industrial-valve-set.mdx",
    "relativePath": "content/products/en/industrial-valve-set.mdx"
  },
  "products/en/led-industrial-lighting": {
    "type": "products",
    "locale": "en",
    "slug": "led-industrial-lighting",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/led-industrial-lighting.mdx",
    "relativePath": "content/products/en/led-industrial-lighting.mdx"
  },
  "products/en/pneumatic-cylinder": {
    "type": "products",
    "locale": "en",
    "slug": "pneumatic-cylinder",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/pneumatic-cylinder.mdx",
    "relativePath": "content/products/en/pneumatic-cylinder.mdx"
  },
  "products/en/smart-sensor-module": {
    "type": "products",
    "locale": "en",
    "slug": "smart-sensor-module",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/smart-sensor-module.mdx",
    "relativePath": "content/products/en/smart-sensor-module.mdx"
  },
  "products/en/stainless-steel-fasteners": {
    "type": "products",
    "locale": "en",
    "slug": "stainless-steel-fasteners",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/stainless-steel-fasteners.mdx",
    "relativePath": "content/products/en/stainless-steel-fasteners.mdx"
  },
  "products/en/variable-frequency-drive": {
    "type": "products",
    "locale": "en",
    "slug": "variable-frequency-drive",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/en/variable-frequency-drive.mdx",
    "relativePath": "content/products/en/variable-frequency-drive.mdx"
  },
  "products/zh/hydraulic-pump-station": {
    "type": "products",
    "locale": "zh",
    "slug": "hydraulic-pump-station",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/hydraulic-pump-station.mdx",
    "relativePath": "content/products/zh/hydraulic-pump-station.mdx"
  },
  "products/zh/industrial-control-panel": {
    "type": "products",
    "locale": "zh",
    "slug": "industrial-control-panel",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/industrial-control-panel.mdx",
    "relativePath": "content/products/zh/industrial-control-panel.mdx"
  },
  "products/zh/industrial-valve-set": {
    "type": "products",
    "locale": "zh",
    "slug": "industrial-valve-set",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/industrial-valve-set.mdx",
    "relativePath": "content/products/zh/industrial-valve-set.mdx"
  },
  "products/zh/led-industrial-lighting": {
    "type": "products",
    "locale": "zh",
    "slug": "led-industrial-lighting",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/led-industrial-lighting.mdx",
    "relativePath": "content/products/zh/led-industrial-lighting.mdx"
  },
  "products/zh/pneumatic-cylinder": {
    "type": "products",
    "locale": "zh",
    "slug": "pneumatic-cylinder",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/pneumatic-cylinder.mdx",
    "relativePath": "content/products/zh/pneumatic-cylinder.mdx"
  },
  "products/zh/smart-sensor-module": {
    "type": "products",
    "locale": "zh",
    "slug": "smart-sensor-module",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/smart-sensor-module.mdx",
    "relativePath": "content/products/zh/smart-sensor-module.mdx"
  },
  "products/zh/stainless-steel-fasteners": {
    "type": "products",
    "locale": "zh",
    "slug": "stainless-steel-fasteners",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/stainless-steel-fasteners.mdx",
    "relativePath": "content/products/zh/stainless-steel-fasteners.mdx"
  },
  "products/zh/variable-frequency-drive": {
    "type": "products",
    "locale": "zh",
    "slug": "variable-frequency-drive",
    "extension": ".mdx",
    "filePath": "/Users/Data/Warehouse/Focus/tucsenberg-web-frontier/content/products/zh/variable-frequency-drive.mdx",
    "relativePath": "content/products/zh/variable-frequency-drive.mdx"
  }
},
} as const;
