import { BREAKPOINT_FULL_HD } from '@/constants';
import { COUNT_4 } from '@/constants/count';
import {
  TEST_APP_CONSTANTS,
  WEB_VITALS_CONSTANTS,
} from '@/constants/test-constants';

/**
 * Web Vitals 性能阈值常量
 */
export const PERFORMANCE_THRESHOLDS = {
  SLOW_RESOURCE_THRESHOLD: WEB_VITALS_CONSTANTS.SLOW_RESOURCE_THRESHOLD,
  MAX_SLOW_RESOURCES: WEB_VITALS_CONSTANTS.MAX_SLOW_RESOURCES,
  CLS_GOOD: WEB_VITALS_CONSTANTS.CLS_GOOD_THRESHOLD,
  CLS_NEEDS_IMPROVEMENT: WEB_VITALS_CONSTANTS.CLS_NEEDS_IMPROVEMENT_THRESHOLD,
  LCP_GOOD: WEB_VITALS_CONSTANTS.LCP_GOOD_THRESHOLD,
  LCP_NEEDS_IMPROVEMENT: WEB_VITALS_CONSTANTS.LCP_NEEDS_IMPROVEMENT_THRESHOLD,
  FID_GOOD: WEB_VITALS_CONSTANTS.FID_GOOD_THRESHOLD,
  FID_NEEDS_IMPROVEMENT: WEB_VITALS_CONSTANTS.FID_NEEDS_IMPROVEMENT_THRESHOLD,
  FCP_GOOD: WEB_VITALS_CONSTANTS.FCP_GOOD_THRESHOLD,
  TTFB_GOOD: WEB_VITALS_CONSTANTS.TTFB_GOOD_THRESHOLD,
  TTFB_NEEDS_IMPROVEMENT: WEB_VITALS_CONSTANTS.TTFB_NEEDS_IMPROVEMENT_THRESHOLD,
  SCORE_WEIGHTS: {
    CLS: WEB_VITALS_CONSTANTS.SCORE_WEIGHT_QUARTER,
    LCP: WEB_VITALS_CONSTANTS.SCORE_WEIGHT_QUARTER,
    FID: WEB_VITALS_CONSTANTS.SCORE_WEIGHT_QUARTER,
    FCP: WEB_VITALS_CONSTANTS.SCORE_WEIGHT_QUARTER,
  },
  SCORE_MULTIPLIERS: {
    GOOD: WEB_VITALS_CONSTANTS.SCORE_MULTIPLIER_GOOD,
    NEEDS_IMPROVEMENT: WEB_VITALS_CONSTANTS.SCORE_MULTIPLIER_NEEDS_IMPROVEMENT,
    POOR: WEB_VITALS_CONSTANTS.SCORE_MULTIPLIER_POOR,
  },
} as const;

/**
 * 设备默认值常量
 */
export const DEVICE_DEFAULTS = {
  MEMORY_GB: COUNT_4,
  CPU_CORES: COUNT_4,
  VIEWPORT_WIDTH: BREAKPOINT_FULL_HD,
  VIEWPORT_HEIGHT: TEST_APP_CONSTANTS.STANDARD_HEIGHT,
} as const;
